import { RequestHandler } from "express";
import { TranslationResponse } from "@shared/api";

// Language code mapping for LibreTranslate
const languageMap: Record<string, string> = {
  en: "en",
  tj: "fa", // Tajik maps to Persian/Farsi for LibreTranslate
  tg: "fa", // Also support legacy code
  ru: "ru",
  fr: "fr",
  es: "es",
  de: "de",
  ar: "ar",
  zh: "zh",
  ja: "ja",
  ko: "ko",
};

// Mock translation database for common words
const mockTranslations: Record<string, Record<string, string>> = {
  ru: {
    en: {
      привет: "hello",
      пока: "goodbye",
      спасибо: "thank you",
      пожалуйста: "please",
      да: "yes",
      нет: "no",
      машина: "car",
      дом: "house",
      кошка: "cat",
      собака: "dog",
      вода: "water",
      огонь: "fire",
      любовь: "love",
      друг: "friend",
      семья: "family",
      красный: "red",
      синий: "blue",
      зеленый: "green",
      желтый: "yellow",
      черный: "black",
      белый: "white",
      фрукт: "fruit",
      яблоко: "apple",
      банан: "banana",
      апельсин: "orange",
      груша: "pear",
      книга: "book",
      стол: "table",
      стул: "chair",
      дверь: "door",
      окно: "window",
      солнце: "sun",
      луна: "moon",
      звезда: "star",
      небо: "sky",
      облако: "cloud",
      дождь: "rain",
      снег: "snow",
      ветер: "wind",
      день: "day",
      ночь: "night",
      утро: "morning",
      вечер: "evening",
      хлеб: "bread",
      молоко: "milk",
      сыр: "cheese",
      масло: "butter",
      яйцо: "egg",
      рис: "rice",
      мясо: "meat",
      рыба: "fish",
      овощ: "vegetable",
      помидор: "tomato",
      картофель: "potato",
      морковь: "carrot",
      школа: "school",
      учитель: "teacher",
      ученик: "student",
      работа: "work",
      отдых: "rest",
      игра: "game",
      музыка: "music",
      песня: "song",
      танец: "dance",
      спорт: "sport",
      мяч: "ball",
      кукла: "doll",
      красивый: "beautiful",
      добрый: "kind",
      плохой: "bad",
      хороший: "good",
      большой: "big",
      маленький: "small",
      старый: "old",
      новый: "new",
      быстрый: "fast",
      медленный: "slow",
      горячий: "hot",
      холодный: "cold",
      тепло: "warm",
      мама: "mother",
      папа: "father",
      сестра: "sister",
      брат: "brother",
      бабушка: "grandmother",
      дедушка: "grandfather",
      мужчина: "man",
      женщина: "woman",
      мальчик: "boy",
      девочка: "girl",
      город: "city",
      страна: "country",
      река: "river",
      гора: "mountain",
      лес: "forest",
      море: "sea",
      озеро: "lake",
      сад: "garden",
      цветок: "flower",
      трава: "grass",
      дерево: "tree",
      листья: "leaves",
      стебель: "stem",
      корень: "root",
      летать: "fly",
      бежать: "run",
      ходить: "walk",
      прыгать: "jump",
      плавать: "swim",
      смеяться: "laugh",
      плакать: "cry",
      спать: "sleep",
      просыпаться: "wake up",
      есть: "eat",
      пить: "drink",
      читать: "read",
      писать: "write",
      говорить: "speak",
      слушать: "listen",
      видеть: "see",
      слышать: "hear",
      нюхать: "smell",
      трогать: "touch",
      забывать: "forget",
      помнить: "remember",
      разумный: "smart",
      глупый: "stupid",
      честный: "honest",
      лживый: "dishonest",
      щедрый: "generous",
      скупой: "stingy",
      смелый: "brave",
      трусливый: "coward",
      радостный: "happy",
      грустный: "sad",
      рассерженный: "angry",
      испуганный: "frightened",
      спокойный: "calm",
      нервный: "nervous",
      уставший: "tired",
      отдохнувший: "rested",
      молодой: "young",
      зрелый: "mature",
      физический: "physical",
      умственный: "mental",
      общественный: "public",
      личный: "private",
      свободный: "free",
      занятый: "busy",
      богатый: "rich",
      бедный: "poor",
      здоровый: "healthy",
      больной: "sick",
      врач: "doctor",
      медсестра: "nurse",
      аптека: "pharmacy",
      больница: "hospital",
      лекарство: "medicine",
      болезнь: "disease",
      здоровье: "health",
      животное: "animal",
      птица: "bird",
      рыба: "fish",
      насекомое: "insect",
      пчела: "bee",
      бабочка: "butterfly",
      муха: "fly",
      комар: "mosquito",
      паук: "spider",
      лошадь: "horse",
      корова: "cow",
      овца: "sheep",
      свинья: "pig",
      курица: "chicken",
      утка: "duck",
      гусь: "goose",
      кролик: "rabbit",
      волк: "wolf",
      лисица: "fox",
      медведь: "bear",
      лев: "lion",
      тигр: "tiger",
      слон: "elephant",
      жираф: "giraffe",
      зебра: "zebra",
      обезьяна: "monkey",
      попугай: "parrot",
      орел: "eagle",
      сова: "owl",
      воробей: "sparrow",
      голубь: "pigeon",
      ворона: "crow",
      кукушка: "cuckoo",
    },
    tj: {
      привет: "салом",
      пока: "хода",
      спасибо: "шукрон",
      пожалуйста: "лутфан",
      да: "ҳа",
      нет: "не",
      машина: "мошин",
      дом: "хона",
      кошка: "гурба",
      собака: "саг",
      вода: "об",
      огонь: "оташ",
      любовь: "муҳаббат",
      друг: "дўст",
      семья: "оила",
      красный: "сурх",
      синий: "кабуд",
      зеленый: "сабз",
      желтый: "зард",
      черный: "сиёҳ",
      белый: "сафед",
      фрукт: "мева",
      яблоко: "себ",
      банан: "банан",
      апельсин: "портқол",
      груша: "нок",
      книга: "китоб",
      стол: "мез",
      стул: "курсӣ",
      дверь: "дар",
      окно: "тирезина",
      солнце: "офтоб",
      луна: "мох",
      звезда: "ситора",
      небо: "осмон",
      облако: "абр",
      дождь: "бороҳ",
      снег: "барф",
      ветер: "бод",
      день: "рӯз",
      ночь: "шаб",
      утро: "саҳар",
      вечер: "шом",
      хлеб: "нон",
      молоко: "шир",
      сыр: "панир",
      масло: "қаймоқ",
      яйцо: "тухм",
      рис: "биринҷ",
      мясо: "гӯшт",
      рыба: "моҳӣ",
      овощ: "сабзавот",
      помидор: "гуп",
      картофель: "сибзамин",
      морковь: "сабзи",
      школа: "мактаб",
      учитель: "муаллим",
      ученик: "шогирд",
      работа: "кор",
      отдых: "истироҳат",
      игра: "бозӣ",
      музыка: "мусиқи",
      песня: "суруд",
      танец: "рақс",
      спорт: "варзиш",
      мяч: "топ",
      кукла: "ҳастии",
      красивый: "қашонг",
      добрый: "неко",
      плохой: "бад",
      хороший: "хуб",
      большой: "бузург",
      маленький: "хурд",
      старый: "қадим",
      новый: "наву",
      быстрый: "зуд",
      медленный: "оҳиста",
      горячий: "гарм",
      холодный: "сард",
      тепло: "ғаплолик",
      мама: "мода",
      папа: "падар",
      сестра: "хоҳар",
      брат: "барадар",
      бабушка: "мамон",
      дедушка: "бобо",
      мужчина: "мард",
      женщина: "занони",
      мальчик: "писар",
      девочка: "духтар",
      город: "шаҳр",
      страна: "кишвар",
      река: "дарё",
      гора: "қуллаи",
      лес: "ҷангал",
      море: "баҳр",
      озеро: "кӯл",
      сад: "боғ",
      цветок: "гул",
      трава: "алаф",
      дерево: "дарахт",
      листья: "барг",
      стебель: "пӯҳ",
      корень: "реша",
      летать: "парвоз",
      бежать: "давидан",
      ходить: "рафтан",
      прыгать: "ҷамп",
      плавать: "шино",
      смеяться: "笑",
      плакать: "гирристан",
      спать: "хоб",
      просыпаться: "бедор",
      есть: "хӯрдан",
      пить: "нӯшидан",
      читать: "хондан",
      писать: "навиштан",
      говорить: "гуфтан",
      слушать: "шунидан",
      видеть: "дидан",
      слышать: "шунифта",
      нюхать: "бӯйидан",
      трогать: "пеҳ",
      забывать: "фарамӯш",
      помнить: "ёддошт",
      разумный: "акл",
      глупый: "ҳамоқ",
      честный: "додрост",
      лживый: "дуруғгӯй",
      щедрый: "сахӣ",
      скупой: "қасса",
      смелый: "дилер",
      трусливый: "трус",
      радостный: "хошҳол",
      грустный: "ғамгин",
      рассерженный: "қаҳр",
      испуганный: "ҳавл",
      спокойный: "оромӣ",
      нервный: "таваттур",
      уставший: "خسته",
      отдохнувший: "истироҳата",
    },
    fr: {
      привет: "bonjour",
      пока: "au revoir",
      спасибо: "merci",
      пожалуйста: "s'il vous plaît",
      да: "oui",
      нет: "non",
      машина: "voiture",
      дом: "maison",
      кошка: "chat",
      собака: "chien",
      вода: "eau",
      огонь: "feu",
      любовь: "amour",
      друг: "ami",
      семья: "famille",
      красный: "rouge",
      синий: "bleu",
      зеленый: "vert",
      желтый: "jaune",
      черный: "noir",
      белый: "blanc",
      яблоко: "pomme",
      банан: "banane",
      апельсин: "orange",
      груша: "poire",
      книга: "livre",
      стол: "table",
      стул: "chaise",
      дверь: "porte",
      окно: "fenêtre",
      солнце: "soleil",
      луна: "lune",
      звезда: "étoile",
      небо: "ciel",
      облако: "nuage",
      дождь: "pluie",
      снег: "neige",
      ветер: "vent",
      день: "jour",
      ночь: "nuit",
      утро: "matin",
      вечер: "soir",
      хлеб: "pain",
      молоко: "lait",
      сыр: "fromage",
      масло: "beurre",
      мама: "mère",
      папа: "père",
      сестра: "sœur",
      брат: "frère",
      мужчина: "homme",
      женщина: "femme",
      мальчик: "garçon",
      девочка: "fille",
      город: "ville",
      страна: "pays",
      река: "fleuve",
      гора: "montagne",
      лес: "forêt",
      море: "mer",
      озеро: "lac",
      цветок: "fleur",
      дерево: "arbre",
      большой: "grand",
      маленький: "petit",
      красивый: "beau",
      хороший: "bon",
      плохой: "mauvais",
    },
    es: {
      привет: "hola",
      пока: "adiós",
      спасибо: "gracias",
      пожалуйста: "por favor",
      да: "sí",
      нет: "no",
      машина: "coche",
      дом: "casa",
      кошка: "gato",
      собака: "perro",
      вода: "agua",
      огонь: "fuego",
      любовь: "amor",
      друг: "amigo",
      семья: "familia",
      красный: "rojo",
      синий: "azul",
      зеленый: "verde",
      желтый: "amarillo",
      черный: "negro",
      белый: "blanco",
      яблоко: "manzana",
      банан: "plátano",
      апельсин: "naranja",
      груша: "pera",
      книга: "libro",
      стол: "mesa",
      стул: "silla",
      дверь: "puerta",
      окно: "ventana",
      солнце: "sol",
      луна: "luna",
      звезда: "estrella",
      небо: "cielo",
      облако: "nube",
      день: "día",
      ночь: "noche",
      утро: "mañana",
      вечер: "tarde",
      хлеб: "pan",
      молоко: "leche",
      сыр: "queso",
      масло: "mantequilla",
      мама: "madre",
      папа: "padre",
      сестра: "hermana",
      брат: "hermano",
      мужчина: "hombre",
      женщина: "mujer",
      мальчик: "niño",
      девочка: "niña",
      город: "ciudad",
      страна: "país",
      река: "río",
      гора: "montaña",
      лес: "bosque",
      море: "mar",
      озеро: "lago",
      цветок: "flor",
      дерево: "árbol",
      большой: "grande",
      маленький: "pequeño",
      красивый: "hermoso",
      хороший: "bueno",
      плохой: "malo",
    },
  },
  en: {
    ru: {
      hello: "привет",
      goodbye: "пока",
      "thank you": "спасибо",
      please: "пожалуйста",
      yes: "да",
      no: "нет",
      car: "машина",
      house: "дом",
      cat: "кошка",
      dog: "собака",
      water: "вода",
      fire: "огонь",
      love: "любовь",
      friend: "друг",
      family: "семья",
      red: "красный",
      blue: "синий",
      green: "зеленый",
      yellow: "желтый",
      black: "черный",
      white: "белый",
      apple: "яблоко",
      banana: "банан",
      orange: "апельсин",
      pear: "груша",
      book: "книга",
      table: "стол",
      chair: "стул",
      door: "дверь",
      window: "окно",
      sun: "солнце",
      moon: "луна",
      star: "звезда",
      sky: "небо",
      cloud: "облако",
      rain: "дождь",
      snow: "снег",
      wind: "ветер",
      day: "день",
      night: "ночь",
      morning: "утро",
      evening: "вечер",
      bread: "хлеб",
      milk: "молоко",
      cheese: "сыр",
      butter: "масло",
      mother: "мама",
      father: "папа",
      sister: "сестра",
      brother: "брат",
      man: "мужчина",
      woman: "женщина",
      boy: "мальчик",
      girl: "девочка",
      city: "город",
      country: "страна",
      river: "река",
      mountain: "гора",
      forest: "лес",
      sea: "море",
      lake: "озеро",
      flower: "цветок",
      tree: "дерево",
      big: "большой",
      small: "маленький",
      beautiful: "красивый",
      good: "хороший",
      bad: "плохой",
      fast: "быстрый",
      slow: "медленный",
      hot: "горячий",
      cold: "холодный",
      happy: "радостный",
      sad: "грустный",
      hungry: "голодный",
      thirsty: "жаждущий",
      tired: "усталый",
      strong: "сильный",
      weak: "слабый",
      tall: "высокий",
      short: "низкий",
      long: "длинный",
      round: "круглый",
      square: "квадратный",
      sweet: "сладкий",
      bitter: "горький",
      salty: "соленый",
      sour: "кислый",
      clean: "чистый",
      dirty: "грязный",
      dry: "сухой",
      wet: "влажный",
      light: "легкий",
      heavy: "тяжелый",
      soft: "мягкий",
      hard: "твердый",
      smooth: "гладкий",
      rough: "шероховатый",
      sharp: "острый",
      dull: "тупой",
      bright: "яркий",
      dark: "темный",
      loud: "громкий",
      quiet: "тихий",
      sweet: "милый",
      sour: "кислый",
      bitter: "горький",
      eat: "есть",
      drink: "пить",
      sleep: "спать",
      walk: "ходить",
      run: "бежать",
      jump: "прыгать",
      swim: "плавать",
      fly: "летать",
      sit: "сидеть",
      stand: "стоять",
      laugh: "смеяться",
      cry: "плакать",
      sing: "петь",
      dance: "танцевать",
      talk: "разговаривать",
      listen: "слушать",
      read: "читать",
      write: "писать",
      draw: "рисовать",
      think: "думать",
      remember: "помнить",
      forget: "забывать",
      understand: "понимать",
      learn: "учиться",
      teach: "учить",
      work: "работать",
      play: "играть",
      rest: "отдыхать",
      travel: "путешествовать",
      drive: "ехать",
      stop: "останавливаться",
      start: "начинать",
      finish: "заканчивать",
      open: "открывать",
      close: "закрывать",
      break: "ломать",
      fix: "чинить",
      build: "строить",
      destroy: "разрушать",
      create: "создавать",
      make: "делать",
      take: "брать",
      give: "давать",
      find: "находить",
      lose: "терять",
      buy: "покупать",
      sell: "продавать",
      price: "цена",
      money: "деньги",
      expensive: "дорогой",
      cheap: "дешевый",
      free: "бесплатный",
      pay: "платить",
      cost: "стоить",
    },
    tj: {
      hello: "салом",
      goodbye: "хода",
      "thank you": "шукрон",
      please: "лутфан",
      yes: "ҳа",
      no: "не",
      car: "мошин",
      house: "хона",
      cat: "гурба",
      dog: "саг",
      water: "об",
      fire: "оташ",
      love: "муҳаббат",
      friend: "дўст",
      family: "оила",
      red: "сурх",
      blue: "кабуд",
      green: "сабз",
      yellow: "зард",
      black: "сиёҳ",
      white: "сафед",
      apple: "себ",
      orange: "портқол",
      pear: "нок",
      book: "китоб",
      table: "мез",
      chair: "курсӣ",
      door: "дар",
      window: "тирезина",
      sun: "офтоб",
      moon: "мох",
      star: "ситора",
      sky: "осмон",
      cloud: "абр",
      rain: "бороҳ",
      snow: "барф",
      wind: "бод",
      day: "рӯз",
      night: "шаб",
      morning: "саҳар",
      evening: "шом",
      bread: "нон",
      milk: "шир",
      cheese: "панир",
      butter: "қаймоқ",
      mother: "мода",
      father: "падар",
      sister: "хоҳар",
      brother: "барадар",
      man: "мард",
      woman: "занони",
      boy: "писар",
      girl: "духтар",
      city: "шаҳр",
      country: "кишвар",
      river: "дарё",
      mountain: "қуллаи",
      forest: "ҷангал",
      sea: "баҳр",
      lake: "кӯл",
      flower: "гул",
      tree: "дарахт",
      big: "бузург",
      small: "хурд",
      beautiful: "қашонг",
      good: "хуб",
      bad: "бад",
      fast: "зуд",
      slow: "оҳиста",
      hot: "гарм",
      cold: "сард",
      happy: "хошҳол",
      sad: "ғамгин",
      hungry: "гӯшнаи",
      thirsty: "тишнаи",
      tired: "خسته",
    },
  },
  tj: {
    ru: {
      салом: "привет",
      хода: "пока",
      шукрон: "спасибо",
      лутфан: "пожалуйста",
      ҳа: "да",
      не: "нет",
      мошин: "машина",
      хона: "дом",
      гурба: "кошка",
      саг: "собака",
      об: "вода",
      оташ: "огонь",
      муҳаббат: "любовь",
      дўст: "друг",
      оила: "семья",
      сурх: "красный",
      кабуд: "синий",
      сабз: "зеленый",
      зард: "желтый",
      сиёҳ: "черный",
      сафед: "белый",
      себ: "яблоко",
      портқол: "апельсин",
      нок: "груша",
      китоб: "книга",
      мез: "стол",
      курсӣ: "стул",
      дар: "дверь",
      тирезина: "окно",
      офтоб: "солнце",
      мох: "луна",
      ситора: "звезда",
      осмон: "небо",
      абр: "облако",
      бороҳ: "дождь",
      барф: "снег",
      бод: "ветер",
      рӯз: "день",
      шаб: "ночь",
      саҳар: "утро",
      шом: "вечер",
      нон: "хлеб",
      шир: "молоко",
      панир: "сыр",
      қаймоқ: "масло",
      мода: "мама",
      падар: "папа",
      хоҳар: "сестра",
      барадар: "брат",
      мард: "мужчина",
      занони: "женщина",
      писар: "мальчик",
      духтар: "девочка",
      шаҳр: "город",
      кишвар: "страна",
      дарё: "река",
      қуллаи: "гора",
      ҷангал: "лес",
      баҳр: "море",
      кӯл: "озеро",
      гул: "цветок",
      дарахт: "дерево",
    },
    en: {
      салом: "hello",
      хода: "goodbye",
      шукрон: "thank you",
      лутфан: "please",
      ҳа: "yes",
      не: "no",
      мошин: "car",
      хона: "house",
      гурба: "cat",
      саг: "dog",
      об: "water",
      оташ: "fire",
      муҳаббат: "love",
      дўст: "friend",
      оила: "family",
      сурх: "red",
      кабуд: "blue",
      сабз: "green",
      зард: "yellow",
      сиёҳ: "black",
      сафед: "white",
      себ: "apple",
      портқол: "orange",
      нок: "pear",
      китоб: "book",
      мез: "table",
      курсӣ: "chair",
      дар: "door",
      тирезина: "window",
      офтоб: "sun",
      мох: "moon",
      ситора: "star",
      осмон: "sky",
      абр: "cloud",
      бороҳ: "rain",
      барф: "snow",
      бод: "wind",
      рӯз: "day",
      шаб: "night",
      саҳар: "morning",
      шом: "evening",
      нон: "bread",
      шир: "milk",
      панир: "cheese",
      қаймоқ: "butter",
      мода: "mother",
      падар: "father",
      хоҳар: "sister",
      барадар: "brother",
      мард: "man",
      занони: "woman",
      писар: "boy",
      духтар: "girl",
      шаҳр: "city",
      кишвар: "country",
      дарё: "river",
      қуллаи: "mountain",
      ҷангал: "forest",
      баҳр: "sea",
      кӯл: "lake",
      гул: "flower",
      дарахт: "tree",
      бузург: "big",
      хурд: "small",
      қашонг: "beautiful",
      хуб: "good",
      бад: "bad",
      зуд: "fast",
      оҳиста: "slow",
      гарм: "hot",
      сард: "cold",
      хошҳол: "happy",
      ғамгин: "sad",
    },
  },
};

function translateWithMock(
  text: string,
  sourceLang: string,
  targetLang: string,
): string {
  if (sourceLang === targetLang) {
    return text;
  }

  const words = text.toLowerCase().trim().split(/\s+/);
  const translations = mockTranslations[sourceLang]?.[targetLang];

  if (!translations) {
    return text; // Return original if no translations available
  }

  const translatedWords = words.map((word) => {
    // Try exact match first
    if (translations[word]) {
      return translations[word];
    }

    // Try without punctuation
    const cleanWord = word.replace(/[.,!?;:]/g, "");
    if (translations[cleanWord]) {
      return translations[cleanWord];
    }

    return word; // Return original word if no translation found
  });

  return translatedWords.join(" ");
}

export const handleTranslate: RequestHandler = async (req, res) => {
  try {
    const { text, sourceLang, targetLang } = req.body;

    if (!text || !sourceLang || !targetLang) {
      return res.status(400).json({
        error: "Missing required fields: text, sourceLang, targetLang",
      });
    }

    const sourceCode = languageMap[sourceLang] || sourceLang;
    const targetCode = languageMap[targetLang] || targetLang;

    // Try mock translation first
    let translatedText = translateWithMock(text, sourceLang, targetLang);

    // Try LibreTranslate API if mock didn't provide full translation
    if (translatedText === text && sourceLang !== targetLang) {
      try {
        const libreResponse = await fetch(
          "https://api.libretranslate.de/translate",
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              q: text,
              source: sourceCode,
              target: targetCode,
            }),
          },
        );

        if (libreResponse.ok) {
          const data = await libreResponse.json();
          translatedText = data.translatedText || text;
        }
      } catch (error) {
        console.error("LibreTranslate error:", error);
        // Continue with mock translation result
      }
    }

    const response: TranslationResponse = {
      originalText: text,
      translatedText,
      sourceLang,
      targetLang,
    };

    res.json(response);
  } catch (error) {
    console.error("Translation error:", error);
    res.status(500).json({ error: "Translation failed" });
  }
};
